#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
OUT_DIR="$ROOT_DIR/docs/audit"
OUT_FILE="$OUT_DIR/dependency-footprint.md"
BASELINE_FILE="$OUT_DIR/dependency-footprint.baseline.md"
DIFF_FILE="$OUT_DIR/dependency-footprint.diff"
TMP_FILE="$(mktemp)"

cleanup() {
  rm -f "$TMP_FILE"
}
trap cleanup EXIT

mkdir -p "$OUT_DIR"

bun_lock_hash="missing"
if [[ -f "$ROOT_DIR/bun.lock" ]]; then
  bun_lock_hash="$(sha256sum "$ROOT_DIR/bun.lock" | awk '{print $1}')"
fi

cargo_lock_state="not-present"
if [[ -f "$ROOT_DIR/apps/desktop/src-tauri/Cargo.lock" ]]; then
  cargo_lock_state="present"
fi

{
  echo "# Dependency Footprint"
  echo
  echo "Generated by \`scripts/audit/deps.sh\`."
  echo
  echo "## Inputs"
  echo
  echo "- \`bun.lock\` SHA-256: \`$bun_lock_hash\`"
  echo "- \`apps/desktop/src-tauri/Cargo.lock\`: \`$cargo_lock_state\`"
  echo
  echo "## JavaScript Dependency Tree (bun list --all)"
  echo
  echo '```text'
  (cd "$ROOT_DIR" && bun list --all)
  echo '```'
  echo
  echo "## Rust Dependency Tree (cargo tree for safelens-desktop)"
  echo
  echo '```text'
  if [[ -f "$ROOT_DIR/apps/desktop/src-tauri/Cargo.lock" ]]; then
    (cd "$ROOT_DIR" && cargo tree --manifest-path apps/desktop/src-tauri/Cargo.toml -p safelens-desktop --locked)
  else
    echo "NOTE: Cargo.lock is not committed for apps/desktop/src-tauri; using unlocked resolution snapshot."
    (cd "$ROOT_DIR" && cargo tree --manifest-path apps/desktop/src-tauri/Cargo.toml -p safelens-desktop)
  fi
  echo '```'
} > "$TMP_FILE"

mv "$TMP_FILE" "$OUT_FILE"

if [[ -f "$BASELINE_FILE" ]]; then
  if diff -u "$BASELINE_FILE" "$OUT_FILE" > "$DIFF_FILE"; then
    echo "No dependency drift vs baseline: $BASELINE_FILE"
  else
    echo "Dependency drift detected. See: $DIFF_FILE"
  fi
else
  echo "No baseline found at $BASELINE_FILE."
fi

echo "Wrote $OUT_FILE"
